baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
hasCJKLanguage = false
# summaryLength = 80
paginate = 3

theme = "../../"

[params]
  # show in HTML meta tag
  author = "Jonn Doe"
  keywords = "HTML, hugo, CSS"
  description = "John Doe's blog"

  # change bulma's primary color
  # primaryColor = "#3e50b4"
  primaryColor = "#1d9bf0"

  # use primary color everywhere, default true
  primaryEverywhere = true

  # change bulma's link color (secondary color in this theme)
  # linkColor = "#ff3f80"

  # subtitle on homepage
  subtitle = "This is a subtitle"

  # copyright text on footer
  copyright = "Copyright Â© 2024 John Doe. All rights reserved."

  # enable katex rendering on every post page, default false
  math = false

  # enable postcss, mainly for css purge (713kB->155kB->20kB gzipped, but this makes build slower), default false
  postcss = true

  # enable showing content summary below post title in home page, default false
  showSummary = true

  # set paginate on taxonomy term page (tags or categories), default 10
  termPaginate = 5

  # enable toc on every post page, default false
  toc = true

  # enable TOC auto collapse, default false
  autoCollapseToc = true

  # enable prefers-color-scheme:dark, default false
  darkMedia = true

  # enable user to toggle dark mode with a menu, default false
  darkToggle = true

  # enable hero section's is-bold effect, default false
  heroBold = false

  # enable hero section that looks like steam deck's home page, default false
  heroSteamDeck = false

  # enable PWA, prepare your icons and DON'T forget to modify manifest.json, default false
  pwa = true

  # disable jsdelivr cdn, default false
  noCDN = false

# for postcss-purgecss
# see https://purgecss.com/guides/hugo.html
[build]
  writeStats = true

# to enable different hightlight themes in light/dark mode
[markup]
[markup.highlight]
noClasses = false

[menu]
  [[menu.main]]
    identifier = "index"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5

[taxonomies]
category = "categories"
tag = "tags"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
